"""empty message

Revision ID: 76d8a56c69ca
Revises: 
Create Date: 2023-10-26 15:58:52.687594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d8a56c69ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('weightclass', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('SigLpM', sa.Float(), nullable=True),
    sa.Column('StrAcc', sa.Float(), nullable=True),
    sa.Column('SApM', sa.Float(), nullable=True),
    sa.Column('StrDef', sa.Float(), nullable=True),
    sa.Column('TDAvg', sa.Float(), nullable=True),
    sa.Column('TDAcc', sa.Float(), nullable=True),
    sa.Column('TDDef', sa.Float(), nullable=True),
    sa.Column('SubAvg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fighters'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('fight_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1_id', sa.Integer(), nullable=True),
    sa.Column('F2_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('F1_opening_odds', sa.Float(), nullable=True),
    sa.Column('F2_opening_odds', sa.Float(), nullable=True),
    sa.Column('F1_closing_odds', sa.Float(), nullable=True),
    sa.Column('F2_closing_odds', sa.Float(), nullable=True),
    sa.Column('Result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['F1_id'], ['fighters.id'], name=op.f('fk_fight_history_F1_id_fighters')),
    sa.ForeignKeyConstraint(['F2_id'], ['fighters.id'], name=op.f('fk_fight_history_F2_id_fighters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fight_history'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('F1_id', sa.Integer(), nullable=True),
    sa.Column('F2_id', sa.Integer(), nullable=True),
    sa.Column('F1_win_prob', sa.Float(), nullable=True),
    sa.Column('F2_win_prob', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['F1_id'], ['fighters.id'], name=op.f('fk_predictions_F1_id_fighters')),
    sa.ForeignKeyConstraint(['F2_id'], ['fighters.id'], name=op.f('fk_predictions_F2_id_fighters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_predictions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('fight_history')
    op.drop_table('users')
    op.drop_table('fighters')
    # ### end Alembic commands ###
