"""empty message

Revision ID: 7717ebdcc378
Revises: 
Create Date: 2023-11-07 02:42:48.952000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7717ebdcc378'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('reach', sa.String(), nullable=True),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('SLpM', sa.Float(), nullable=True),
    sa.Column('Str_Acc', sa.Float(), nullable=True),
    sa.Column('SApM', sa.Float(), nullable=True),
    sa.Column('Str_Def', sa.Float(), nullable=True),
    sa.Column('TD_Avg', sa.Float(), nullable=True),
    sa.Column('TD_Acc', sa.Float(), nullable=True),
    sa.Column('TD_Def', sa.Float(), nullable=True),
    sa.Column('Sub_Avg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fighters'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('fight_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('F1_id', sa.Integer(), nullable=True),
    sa.Column('F2_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('Result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['F1_id'], ['fighters.id'], name=op.f('fk_fight_history_F1_id_fighters')),
    sa.ForeignKeyConstraint(['F2_id'], ['fighters.id'], name=op.f('fk_fight_history_F2_id_fighters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fight_history'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('F1_id', sa.Integer(), nullable=True),
    sa.Column('F2_id', sa.Integer(), nullable=True),
    sa.Column('F1_win_prob', sa.Float(), nullable=True),
    sa.Column('F2_win_prob', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['F1_id'], ['fighters.id'], name=op.f('fk_predictions_F1_id_fighters')),
    sa.ForeignKeyConstraint(['F2_id'], ['fighters.id'], name=op.f('fk_predictions_F2_id_fighters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_predictions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('fight_history')
    op.drop_table('users')
    op.drop_table('fighters')
    # ### end Alembic commands ###
